### ISSUE TITLE
Old generator

### ISSUE THREAD

**Issue by NavyHusky** [dcgruenig/Minecraft-Vanilla-Sign-Shop-Generator#1]
Hey man! Is it possible that you can change the generator? Because it says ''sign'' but it need to be ''oak_sign'' and also can you change ''money'' to ''Money'' ? Like to hear from you!

Kinds regards,

**Comment by dcgruenig** [comment]
It took a while to get motivated to fix this, but I finally did. Now you can change the sign type for older or current versions of Minecraft.

**Comment by NavyHusky** [comment]
Thank you so much mate! Your work is appreciated :)
